name: Monitor Booking
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: |
          npm init -y
          npm install playwright
          npx playwright install chromium
      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
        run: node monitor.js
